[project]
name = "python-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click",
    "rich",
    # `bitstream` requires pip, so it's harder to use with uv out of the box
    "bitstring"
]

[dependency-groups]
dev = [
    "ipython",
]
test = [
    "pytest",
]

[project.scripts]
huffman = "clis.huffman:main"
activities = "clis.activities:main"
lcs = "clis.longest_common_substring:main"

[tool.uv]
package = true
